title: Rakis Productions
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.7860743
  brandStrength: 1
  lightness: 0.327957
  brandColors:
    - '#ADADAD'
    - '#010101'
    - '#424242'
    - '#7C7C7C'
    - '#FDECB5'
  rhythmicContrast: 0.980872
cta:
  bucket: null
  version: null
  domain: null
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Rakis Productions
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.9040247346274555
layout_spectrum: 0
