name: Rakis Productions
favicon: null
layout_spectrum: 0.9982079
typography_spectrum: 0.9040247346274555
title: Rakis Productions
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fd89e9'
    - '#feb7f1'
    - '#4e3249'
    - '#6c5066'
  brandStrength: 1
  lightness: 0.3274168148636818
  saturation: 0.7860742984339595
  rhythmicContrast: 0.9808720434084535
purpose: []
